blank_issues_enabled: true
contact_links:
  - name: ğŸ¥ Visual Effects Video Playlist 
    url: https://www.youtube.com/playlist?list=PLEwYhelKHmig6ttzH0nRL3OOQsGLtVrtX
    about: View the Visual Effects examples playlist on YouTube
  - name: ğŸ‘©â€ğŸ’» World of Zero Discord Server
    url: https://discord.gg/T32BESf
    about: Join the World of Zero Discord server to share how your using these effects or to ask questions about them